"""Production navigation pins do not certify live device acceptance."""
import json
import unittest
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
EXPECTED = {'ha-ho-sc-8w': {'artifacts': [{'binding_limitations': [],
                                'bindings': [{'expected': 'irrigation-panel.js',
                                              'path': 'custom_components/nikas_ho_sc_8w/const.py',
                                              'path_mode': 'basename',
                                              'pattern': '(?m)^PANEL_JS_URL\\s*=\\s*f[\\"\\x27]\\{PANEL_STATIC_URL\\}/(?P<value>[^\\"\\x27?\\r\\n]+)[\\"\\x27]',
                                              'role': 'entrypoint'},
                                             {'expected': '1.1.1',
                                              'path': 'custom_components/nikas_ho_sc_8w/frontend/irrigation-panel.js',
                                              'pattern': '(?m)^\\s*(?:const\\s+)?NIKAS_HO_SC_8W_UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                              'role': 'ui_version'},
                                             {'expected': '1.1.1',
                                              'path': 'custom_components/nikas_ho_sc_8w/const.py',
                                              'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                              'role': 'cache_key'}],
                                'id': 'panel',
                                'path': 'custom_components/nikas_ho_sc_8w/frontend/irrigation-panel.js',
                                'registration_evidence_paths': ['custom_components/nikas_ho_sc_8w/frontend.py',
                                                                'custom_components/nikas_ho_sc_8w/const.py',
                                                                'custom_components/nikas_ho_sc_8w/__init__.py'],
                                'ui_version': '1.1.1'}],
                 'pr': 182,
                 'sha': '8e4e1bf755105a3bef88ca6bfa04175bc5c5d4c6',
                 'url': 'https://github.com/NikaSir/ha-ho-sc-8w/pull/182'},
 'ha-keenetic-hero-4g': {'artifacts': [{'binding_limitations': ['panel_runtime._select_frontend overrides '
                                                                'legacy panel.PANEL_MODULE. Static binding '
                                                                'inventories the override; behavioral proof '
                                                                'of the selector and effective UI is '
                                                                'pending.'],
                                        'bindings': [{'expected': 'keenetic-panel-bundle.js',
                                                      'path': 'custom_components/keenetic_hero_4g/panel_runtime.py',
                                                      'path_mode': 'basename',
                                                      'pattern': 'f[\\"\\x27]\\{_panel\\.PANEL_STATIC_URL\\}/(?P<value>[^\\"\\x27?\\r\\n]+)\\?v=\\{FRONTEND_CACHE_KEY\\}',
                                                      'role': 'entrypoint'},
                                                     {'expected': '1.0.12',
                                                      'path': 'custom_components/keenetic_hero_4g/frontend/keenetic-panel-bundle.js',
                                                      'pattern': '(?m)^\\s*(?:const\\s+)?K100_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                      'role': 'ui_version'},
                                                     {'expected': '1.0.12',
                                                      'path': 'custom_components/keenetic_hero_4g/panel_runtime.py',
                                                      'pattern': '(?m)^\\s*(?:const\\s+)?FRONTEND_CACHE_KEY\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                      'role': 'cache_key'}],
                                        'id': 'panel',
                                        'path': 'custom_components/keenetic_hero_4g/frontend/keenetic-panel-bundle.js',
                                        'registration_evidence_paths': ['custom_components/keenetic_hero_4g/__init__.py',
                                                                        'custom_components/keenetic_hero_4g/panel_runtime.py',
                                                                        'custom_components/keenetic_hero_4g/panel.py'],
                                        'ui_version': '1.0.12'}],
                         'pr': 96,
                         'sha': '40668e90b71484baba2dd2279aa1281e2be3cd8c',
                         'url': 'https://github.com/NikaSir/ha-keenetic-hero-4g/pull/96'},
 'ha-lider-voltage-control': {'artifacts': [{'binding_limitations': [],
                                             'bindings': [{'expected': 'lider-voltage-control-panel.js',
                                                           'path': 'custom_components/lider_voltage_control/panel.py',
                                                           'path_mode': 'basename',
                                                           'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_BUNDLE\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                           'role': 'entrypoint'},
                                                          {'expected': '0.8.10',
                                                           'path': 'custom_components/lider_voltage_control/frontend/lider-voltage-control-panel.js',
                                                           'pattern': '(?m)^\\s*(?:const\\s+)?LIDER_UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                           'role': 'ui_version'},
                                                          {'expected': '0.8.10',
                                                           'path': 'custom_components/lider_voltage_control/panel.py',
                                                           'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                           'role': 'cache_key'}],
                                             'id': 'panel',
                                             'path': 'custom_components/lider_voltage_control/frontend/lider-voltage-control-panel.js',
                                             'registration_evidence_paths': ['custom_components/lider_voltage_control/__init__.py',
                                                                             'custom_components/lider_voltage_control/panel.py'],
                                             'ui_version': '0.8.10'}],
                              'pr': 46,
                              'sha': '03dcc945f22f2d8506d1db857706748198566e88',
                              'url': 'https://github.com/NikaSir/ha-lider-voltage-control/pull/46'},
 'ha-nikas-access': {'artifacts': [{'binding_limitations': [],
                                    'bindings': [{'expected': 'nikas-access-panel.js',
                                                  'path': 'custom_components/nikas_access/panel.py',
                                                  'path_mode': 'basename',
                                                  'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_BUNDLE\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                  'role': 'entrypoint'},
                                                 {'expected': '0.1.10',
                                                  'path': 'custom_components/nikas_access/frontend/nikas-access-panel.js',
                                                  'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                  'role': 'ui_version'},
                                                 {'expected': '0.1.10',
                                                  'path': 'custom_components/nikas_access/const.py',
                                                  'pattern': '(?m)^\\s*(?:const\\s+)?VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                  'role': 'cache_key'}],
                                    'id': 'panel',
                                    'path': 'custom_components/nikas_access/frontend/nikas-access-panel.js',
                                    'registration_evidence_paths': ['custom_components/nikas_access/__init__.py',
                                                                    'custom_components/nikas_access/panel.py'],
                                    'ui_version': '0.1.10'}],
                     'pr': 14,
                     'sha': '29ad98ac191d210f36c75ed2fde24844637efaf4',
                     'url': 'https://github.com/NikaSir/ha-nikas-access/pull/14'},
 'ha-nikas-climate': {'artifacts': [{'binding_limitations': ['The autonomous production bundle retains '
                                                             'historical source version constants. The '
                                                             'current overlay declares UI161=1.4.29 and Home '
                                                             'Assistant registers '
                                                             'nikas-climate-production.js with '
                                                             'integration/cache version 0.1.58. Live client '
                                                             'cache/display acceptance remains pending.'],
                                     'bindings': [{'expected': 'nikas-climate-production.js',
                                                   'path': 'custom_components/nikas_climate/panel.py',
                                                   'path_mode': 'basename',
                                                   'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_BUNDLE\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                   'role': 'entrypoint'},
                                                  {'expected': '1.4.29',
                                                   'path': 'custom_components/nikas_climate/frontend/nikas-climate-production.js',
                                                   'pattern': '(?m)^\\s*(?:const\\s+)?UI161\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                   'role': 'ui_version'},
                                                  {'expected': '0.1.58',
                                                   'path': 'custom_components/nikas_climate/const.py',
                                                   'pattern': '(?m)^\\s*(?:const\\s+)?VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                   'role': 'cache_key'}],
                                     'id': 'panel',
                                     'path': 'custom_components/nikas_climate/frontend/nikas-climate-production.js',
                                     'registration_evidence_paths': ['custom_components/nikas_climate/__init__.py',
                                                                     'custom_components/nikas_climate/panel.py',
                                                                     'custom_components/nikas_climate/const.py'],
                                     'ui_version': '1.4.29'}],
                      'pr': 20,
                      'sha': '1c98b256df93a6793708a9462eef392ff1cdf858',
                      'url': 'https://github.com/NikaSir/ha-nikas-climate/pull/20'},
 'ha-nikas-dyson': {'artifacts': [{'binding_limitations': [],
                                   'bindings': [{'expected': 'nikas-dyson-panel.js',
                                                 'path': 'custom_components/nikas_dyson/__init__.py',
                                                 'path_mode': 'basename',
                                                 'pattern': 'module_url=f"/nikas_dyson_static/(?P<value>[^?"\\r\\n]+)\\?v=\\{UI_VERSION\\}"',
                                                 'role': 'entrypoint'},
                                                {'expected': '1.0.3',
                                                 'path': 'custom_components/nikas_dyson/frontend/nikas-dyson-panel.js',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*["\\x27](?P<value>[^"\\x27\\r\\n]+)["\\x27]',
                                                 'role': 'ui_version'},
                                                {'expected': '1.0.3',
                                                 'path': 'custom_components/nikas_dyson/const.py',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*["\\x27](?P<value>[^"\\x27\\r\\n]+)["\\x27]',
                                                 'role': 'cache_key'},
                                                {'expected': '0.1.6',
                                                 'path': 'custom_components/nikas_dyson/const.py',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?VERSION\\s*=\\s*["\\x27](?P<value>[^"\\x27\\r\\n]+)["\\x27]',
                                                 'role': 'integration_version'}],
                                   'id': 'panel',
                                   'path': 'custom_components/nikas_dyson/frontend/nikas-dyson-panel.js',
                                   'registration_evidence_paths': ['custom_components/nikas_dyson/__init__.py',
                                                                   'custom_components/nikas_dyson/panel_manifest.json'],
                                   'ui_version': '1.0.3'}],
                    'pr': 3,
                    'sha': '2a246b263ad3fb0398a4ee662e0c1e7a0ffeaae9',
                    'url': 'https://github.com/NikaSir/ha-nikas-dyson/pull/3'},
 'ha-nikas-house': {'artifacts': [{'binding_limitations': ['HOUSE_PANEL_FILENAME uses dist/ relative to the '
                                                           'frontend directory. Registration evidence '
                                                           'establishes the directory; cache build freshness '
                                                           'across changes is not established by this '
                                                           'snapshot.'],
                                   'bindings': [{'expected': 'dist/nikas-house-overview.js',
                                                 'path': 'custom_components/nikas_house/const.py',
                                                 'path_mode': 'basename',
                                                 'pattern': '(?m)^HOUSE_PANEL_FILENAME\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'entrypoint'},
                                                {'expected': '1.0.3',
                                                 'path': 'custom_components/nikas_house/frontend/dist/nikas-house-overview.js',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'ui_version'},
                                                {'expected': 'v1_0_3_b001',
                                                 'path': 'custom_components/nikas_house/const.py',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?HOUSE_PANEL_BUILD\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'cache_key'}],
                                   'id': 'panel',
                                   'path': 'custom_components/nikas_house/frontend/dist/nikas-house-overview.js',
                                   'registration_evidence_paths': ['custom_components/nikas_house/__init__.py',
                                                                   'custom_components/nikas_house/house_panel.py',
                                                                   'custom_components/nikas_house/const.py'],
                                   'ui_version': '1.0.3'},
                                  {'binding_limitations': ['Registered through add_extra_js_url, '
                                                           'independently of the panel module. No '
                                                           'independent UI version is declared; build key is '
                                                           'recorded as cache evidence only. Effective '
                                                           'startup, absence of global side effects and '
                                                           'cache freshness require runtime acceptance.'],
                                   'bindings': [{'expected': 'nikas-ui.js',
                                                 'path': 'custom_components/nikas_house/const.py',
                                                 'path_mode': 'basename',
                                                 'pattern': '(?m)^UI_BUNDLE_FILENAME\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'entrypoint'},
                                                {'expected': 'v1_0_3_b001',
                                                 'path': 'custom_components/nikas_house/const.py',
                                                 'pattern': '(?m)^UI_BUNDLE_BUILD\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'cache_key'}],
                                   'id': 'navigation',
                                   'path': 'custom_components/nikas_house/frontend/nikas-ui.js',
                                   'registration_evidence_paths': ['custom_components/nikas_house/__init__.py',
                                                                   'custom_components/nikas_house/const.py'],
                                   'ui_version': 'not_declared'},
                                  {'binding_limitations': ['Registered through add_extra_js_url, '
                                                           'independently of the panel module. No '
                                                           'independent UI version is declared; build key is '
                                                           'recorded as cache evidence only. Effective '
                                                           'startup, absence of global side effects and '
                                                           'cache freshness require runtime acceptance.'],
                                   'bindings': [{'expected': 'nikas-house-hero.js',
                                                 'path': 'custom_components/nikas_house/const.py',
                                                 'path_mode': 'basename',
                                                 'pattern': '(?m)^HOUSE_HERO_FILENAME\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'entrypoint'},
                                                {'expected': 'v1_0_3_b001',
                                                 'path': 'custom_components/nikas_house/const.py',
                                                 'pattern': '(?m)^HOUSE_HERO_BUILD\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'cache_key'}],
                                   'id': 'hero',
                                   'path': 'custom_components/nikas_house/frontend/nikas-house-hero.js',
                                   'registration_evidence_paths': ['custom_components/nikas_house/__init__.py',
                                                                   'custom_components/nikas_house/const.py'],
                                   'ui_version': 'not_declared'}],
                    'pr': 12,
                    'sha': '97f7d137f54c891a6acea69d84aa2da9de2ae453',
                    'url': 'https://github.com/NikaSir/ha-nikas-house/pull/12'},
 'ha-nikas-rooms': {'artifacts': [{'binding_limitations': [],
                                   'bindings': [{'expected': 'nikas-rooms-panel.js',
                                                 'path': 'custom_components/nikas_rooms/panel.py',
                                                 'path_mode': 'basename',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_BUNDLE\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'entrypoint'},
                                                {'expected': '11.0.16',
                                                 'path': 'custom_components/nikas_rooms/frontend/nikas-rooms-panel.js',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'ui_version'},
                                                {'expected': '11.0.16',
                                                 'path': 'custom_components/nikas_rooms/panel.py',
                                                 'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                 'role': 'cache_key'}],
                                   'id': 'panel',
                                   'path': 'custom_components/nikas_rooms/frontend/nikas-rooms-panel.js',
                                   'registration_evidence_paths': ['custom_components/nikas_rooms/__init__.py',
                                                                   'custom_components/nikas_rooms/panel.py'],
                                   'ui_version': '11.0.16'}],
                    'pr': 8,
                    'sha': 'ed3f7e50b2c9756fddd9f2a79dc14f82f09e8fdc',
                    'url': 'https://github.com/NikaSir/ha-nikas-rooms/pull/8'},
 'ha-s8-omni': {'artifacts': [{'binding_limitations': [],
                               'bindings': [{'expected': 's8-omni-production.js',
                                             'path': 'custom_components/s8_omni/__init__.py',
                                             'path_mode': 'basename',
                                             'pattern': '(?m)^PANEL_MODULE\\s*=\\s*f[\\"\\x27]\\{PANEL_STATIC_URL\\}/(?P<value>[^\\"\\x27?\\r\\n]+)\\?v=',
                                             'role': 'entrypoint'},
                                            {'expected': 'v1.0.8',
                                             'path': 'custom_components/s8_omni/frontend/s8-omni-panel.js',
                                             'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                             'role': 'ui_version'},
                                            {'expected': 'v1.0.8',
                                             'path': 'custom_components/s8_omni/const.py',
                                             'pattern': '(?m)^\\s*(?:const\\s+)?DASHBOARD_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                             'role': 'cache_key'}],
                               'id': 'panel',
                               'path': 'custom_components/s8_omni/frontend/s8-omni-production.js',
                               'registration_evidence_paths': ['custom_components/s8_omni/__init__.py',
                                                               'custom_components/s8_omni/const.py'],
                               'ui_version': 'v1.0.8'}],
                'pr': 134,
                'sha': '0780c62f793f95bd941d4b377dfcf2724168342e',
                'url': 'https://github.com/NikaSir/ha-s8-omni/pull/134'},
 'ha-stark-solarpower': {'artifacts': [{'binding_limitations': ['The bundle retains historical scoped '
                                                                'UI_VERSION declarations. The binding '
                                                                'selects the v098 overview-header patch; '
                                                                'registration/cache metadata also declares '
                                                                '0.9.8. Live patch ordering and '
                                                                'displayed-version acceptance remain '
                                                                'pending.'],
                                        'bindings': [{'expected': 'stark-solarpower-panel-bundle.js',
                                                      'path': 'custom_components/stark_solarpower/panel.py',
                                                      'path_mode': 'basename',
                                                      'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_BUNDLE\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                      'role': 'entrypoint'},
                                                     {'expected': '0.9.8',
                                                      'path': 'custom_components/stark_solarpower/frontend/stark-solarpower-panel-bundle.js',
                                                      'pattern': '(?m)^const '
                                                                 'UI_VERSION\\s*=\\s*"(?P<value>[^"\\r\\n]+)";\\s*\\n\\s*if '
                                                                 '\\(Panel && '
                                                                 '!Panel\\.prototype\\.__starkUiV098\\)',
                                                      'role': 'ui_version'},
                                                     {'expected': '0.9.8',
                                                      'path': 'custom_components/stark_solarpower/panel.py',
                                                      'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                      'role': 'cache_key'}],
                                        'id': 'panel',
                                        'path': 'custom_components/stark_solarpower/frontend/stark-solarpower-panel-bundle.js',
                                        'registration_evidence_paths': ['custom_components/stark_solarpower/__init__.py',
                                                                        'custom_components/stark_solarpower/panel.py'],
                                        'ui_version': '0.9.8'}],
                         'pr': 77,
                         'sha': '331a7dcad89cc8e85d9a4c93f200828175c022db',
                         'url': 'https://github.com/NikaSir/ha-stark-solarpower/pull/77'},
 'ha-starline-telemetry': {'artifacts': [{'binding_limitations': [],
                                          'bindings': [{'expected': 'starline-app.js',
                                                        'path': 'custom_components/starline_telemetry/panel.py',
                                                        'path_mode': 'basename',
                                                        'pattern': '(?m)^PANEL_MODULE\\s*=\\s*f[\\"\\x27]\\{PANEL_STATIC_URL\\}/(?P<value>[^\\"\\x27?\\r\\n]+)\\?v=',
                                                        'role': 'entrypoint'},
                                                       {'expected': '0.6.10',
                                                        'path': 'custom_components/starline_telemetry/frontend/starline-app.js',
                                                        'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                        'role': 'ui_version'},
                                                       {'expected': '0.6.10-ui-standard-v2.2',
                                                        'path': 'custom_components/starline_telemetry/const.py',
                                                        'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                        'role': 'cache_key'}],
                                          'id': 'panel',
                                          'path': 'custom_components/starline_telemetry/frontend/starline-app.js',
                                          'registration_evidence_paths': ['custom_components/starline_telemetry/__init__.py',
                                                                          'custom_components/starline_telemetry/panel.py',
                                                                          'custom_components/starline_telemetry/const.py'],
                                          'ui_version': '0.6.10'}],
                           'pr': 60,
                           'sha': 'ecbe026ba7e785265c3d2a746e97d529998443d8',
                           'url': 'https://github.com/NikaSir/ha-starline-telemetry/pull/60'},
 'ha-vless-gateway': {'artifacts': [{'binding_limitations': [],
                                     'bindings': [{'expected': 'vless-gateway-panel.js',
                                                   'path': 'custom_components/vless_gateway/panel.py',
                                                   'path_mode': 'basename',
                                                   'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_BUNDLE\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                   'role': 'entrypoint'},
                                                  {'expected': '0.1.2',
                                                   'path': 'custom_components/vless_gateway/frontend/vless-gateway-panel.js',
                                                   'pattern': '(?m)^\\s*uiVersion\\s*:\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                   'role': 'ui_version'},
                                                  {'expected': '0.1.2',
                                                   'path': 'custom_components/vless_gateway/const.py',
                                                   'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                   'role': 'cache_key'}],
                                     'id': 'panel',
                                     'path': 'custom_components/vless_gateway/frontend/vless-gateway-panel.js',
                                     'registration_evidence_paths': ['custom_components/vless_gateway/__init__.py',
                                                                     'custom_components/vless_gateway/panel.py'],
                                     'ui_version': '0.1.2'}],
                      'pr': 24,
                      'sha': '532d45fecd5cd7622be875437da02ff6060252f8',
                      'url': 'https://github.com/NikaSir/ha-vless-gateway/pull/24'},
 'ha-water-accounting': {'artifacts': [{'binding_limitations': [],
                                        'bindings': [{'expected': 'water-accounting-panel.js',
                                                      'path': 'custom_components/water_accounting/panel.py',
                                                      'path_mode': 'basename',
                                                      'pattern': '(?m)^\\s*(?:const\\s+)?PANEL_BUNDLE\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                      'role': 'entrypoint'},
                                                     {'expected': '0.1.6',
                                                      'path': 'custom_components/water_accounting/frontend/water-accounting-panel.js',
                                                      'pattern': '(?m)^\\s*uiVersion\\s*:\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                      'role': 'ui_version'},
                                                     {'expected': '0.1.6',
                                                      'path': 'custom_components/water_accounting/const.py',
                                                      'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                                      'role': 'cache_key'}],
                                        'id': 'panel',
                                        'path': 'custom_components/water_accounting/frontend/water-accounting-panel.js',
                                        'registration_evidence_paths': ['custom_components/water_accounting/__init__.py',
                                                                        'custom_components/water_accounting/panel.py'],
                                        'ui_version': '0.1.6'}],
                         'pr': 7,
                         'sha': '889c22f44ce56559eede919099340c48ead1c386',
                         'url': 'https://github.com/NikaSir/ha-water-accounting/pull/7'},
 'ha-zont': {'artifacts': [{'binding_limitations': [],
                            'bindings': [{'expected': 'zont-ui.js',
                                          'path': 'custom_components/zont_local/const.py',
                                          'path_mode': 'basename',
                                          'pattern': '(?m)^\\s*(?:const\\s+)?FRONTEND_FILENAME\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                          'role': 'entrypoint'},
                                         {'expected': '0.9.7',
                                          'path': 'custom_components/zont_local/frontend/zont-ui.js',
                                          'pattern': '(?m)^\\s*(?:const\\s+)?UI_VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                          'role': 'ui_version'},
                                         {'expected': '0.9.7',
                                          'path': 'custom_components/zont_local/const.py',
                                          'pattern': '(?m)^\\s*(?:const\\s+)?VERSION\\s*=\\s*[\\"\\x27](?P<value>[^\\"\\x27\\r\\n]+)[\\"\\x27]',
                                          'role': 'cache_key'}],
                            'id': 'panel',
                            'path': 'custom_components/zont_local/frontend/zont-ui.js',
                            'registration_evidence_paths': ['custom_components/zont_local/__init__.py',
                                                            'custom_components/zont_local/const.py'],
                            'ui_version': '0.9.7'}],
             'pr': 34,
             'sha': '9ca0f4eb6b4a9c8ab7e128ed75560e48c38e19e3',
             'url': 'https://github.com/NikaSir/ha-zont/pull/34'}}

class HeaderNavigationReconciliationTests(unittest.TestCase):
    def test_production_profiles_preserve_acceptance_boundary(self):
        for repo, expected in EXPECTED.items():
            with self.subTest(repository=repo):
                profile = json.loads((ROOT / "deployments/repository-contracts" / (repo + ".json")).read_text())
                self.assertIsNotNone(expected["sha"])
                self.assertEqual(profile["source_revision"], expected["sha"])
                self.assertEqual(profile["artifacts"], expected["artifacts"])
                finding = next(f for f in profile["findings"] if f["id"] == "NAV-1")
                self.assertEqual(finding["status"], "fixed_pending_verification")
                self.assertIn("PR #" + str(expected["pr"]), finding["note"])
                self.assertIn("/home/overview", finding["note"])
                evidence = {e["requirement"]: e for e in profile["evidence"]}
                self.assertTrue(all(e["status"] == "pending" for e in evidence.values()))
                self.assertEqual(evidence["device_acceptance"]["paths"], [])

if __name__ == "__main__":
    unittest.main()
