"""Constants for Contract Generated UI."""

from datetime import timedelta

DOMAIN = "contract_generated_ui"
NAME = "Contract Generated UI"

SOURCE_DIRECTORY = "contract_generated_ui"
SOURCE_KINDS = ("contracts", "inventory", "manifests", "navigation")
SOURCE_STATUSES = ("missing", "empty", "incomplete", "valid", "invalid")
SNAPSHOT_DIRECTORY = "snapshots"
GENERATED_DIRECTORY = "generated"
FRONTEND_DIRECTORY = "frontend"
APP_SHELL_FILENAME = "nikas-app-shell.js"
APP_SHELL_STATIC_PATH = f"/{DOMAIN}/frontend/{APP_SHELL_FILENAME}"
INFRA_SUMMARY_FILENAME = "nikas-infrastructure-summary.js"
INFRA_SUMMARY_STATIC_PATH = f"/{DOMAIN}/frontend/{INFRA_SUMMARY_FILENAME}"
INFRASTRUCTURE_PANEL_FILENAME = "nikas-infrastructure-overview.js"
INFRASTRUCTURE_PANEL_STATIC_PATH = f"/{DOMAIN}/frontend/{INFRASTRUCTURE_PANEL_FILENAME}"
INFRASTRUCTURE_PANEL_BUILD = "b001"
INFRASTRUCTURE_PANEL_MODULE_URL = (
    f"{INFRASTRUCTURE_PANEL_STATIC_PATH}?build={INFRASTRUCTURE_PANEL_BUILD}"
)
INFRASTRUCTURE_PANEL_PATH = "infrastructure_panel_path"
UI_BUNDLE_FILENAME = "nikas-ui.js"
UI_BUNDLE_STATIC_PATH = f"/{DOMAIN}/frontend/{UI_BUNDLE_FILENAME}"
UI_BUNDLE_BUILD = "b007"
UI_BUNDLE_MODULE_URL = f"{UI_BUNDLE_STATIC_PATH}?build={UI_BUNDLE_BUILD}"
PANEL_ZOOM_FILENAME = "nikas-panel-zoom.js"
PANEL_ZOOM_STATIC_PATH = f"/{DOMAIN}/frontend/{PANEL_ZOOM_FILENAME}"
PANEL_ZOOM_BUILD = "b002"
PANEL_ZOOM_MODULE_URL = f"{PANEL_ZOOM_STATIC_PATH}?build={PANEL_ZOOM_BUILD}"
SPECIALIZED_SHELL_FILENAME = "nikas-specialized-panel-shell.js"
SPECIALIZED_SHELL_STATIC_PATH = f"/{DOMAIN}/frontend/{SPECIALIZED_SHELL_FILENAME}"
SPECIALIZED_SHELL_BUILD = "b002"
SPECIALIZED_SHELL_MODULE_URL = f"{SPECIALIZED_SHELL_STATIC_PATH}?build={SPECIALIZED_SHELL_BUILD}"
HOUSE_HERO_FILENAME = "nikas-house-hero.js"
HOUSE_HERO_STATIC_PATH = f"/{DOMAIN}/frontend/{HOUSE_HERO_FILENAME}"
HOUSE_HERO_BUILD = "b009"
HOUSE_HERO_MODULE_URL = f"{HOUSE_HERO_STATIC_PATH}?build={HOUSE_HERO_BUILD}"
HOUSE_PANEL_FILENAME = "nikas-house-overview.js"
HOUSE_PANEL_STATIC_PATH = f"/{DOMAIN}/frontend/{HOUSE_PANEL_FILENAME}"
HOUSE_PANEL_BUILD = "b002"
HOUSE_PANEL_MODULE_URL = f"{HOUSE_PANEL_STATIC_PATH}?build={HOUSE_PANEL_BUILD}"
HOUSE_HERO_ASSETS_STATIC_PATH = f"/{DOMAIN}/frontend/assets"
HOUSE_HERO_ASSET_FILENAME = "house-hero-photo-day-v3.webp"
HOUSE_HERO_ASSET_BUILD = "0340b001"
HOUSE_HERO_ASSET_URL = (
    f"{HOUSE_HERO_ASSETS_STATIC_PATH}/{HOUSE_HERO_ASSET_FILENAME}?build={HOUSE_HERO_ASSET_BUILD}"
)
GENERATED_SUBPANEL_FILENAME = "nikas-generated-subpanel.js"
GENERATED_SUBPANEL_STATIC_PATH = f"/{DOMAIN}/frontend/{GENERATED_SUBPANEL_FILENAME}"
GENERATED_SUBPANEL_BUILD = "b006"
GENERATED_SUBPANEL_MODULE_URL = (
    f"{GENERATED_SUBPANEL_STATIC_PATH}?build={GENERATED_SUBPANEL_BUILD}"
)
GENERATED_SUBPANEL_PATHS = "generated_subpanel_paths"
HOUSE_PANEL_PATH = "house_panel_path"
NAVIGATION_REGISTRY_FILENAME = "navigation.json"
NAVIGATION_REGISTRY_STATIC_PATH = f"/{DOMAIN}/{NAVIGATION_REGISTRY_FILENAME}"
FRONTEND_STATIC_REGISTERED = "frontend_static_registered"

SCAN_INTERVAL = timedelta(minutes=1)

ATTR_CONTRACTS = "contracts"
ATTR_INVENTORY = "inventory"
ATTR_MANIFESTS = "manifests"
ATTR_NAVIGATION = "navigation"
ATTR_DOCUMENT_COUNT = "document_count"
ATTR_ISSUE_COUNT = "issue_count"
ATTR_ISSUES = "issues"
ATTR_SOURCE_DIRECTORY = "source_directory"
ATTR_VALIDATION_LEVEL = "validation_level"

VALIDATION_LEVEL = "contract_core_v1"
MAX_ISSUES_IN_ATTRIBUTES = 10
